# Generated by Django 4.0 on 2021-12-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowyourinstitution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='college',
            name='program',
            field=models.CharField(max_length=50),
        ),
    ]
